### ISSUE TITLE
UAF 1.1 Authentication Test F-27

### ISSUE THREAD

**Issue by k-tono** [fido-alliance/conformance-tool-issues#56] opened 2017-11-14 08:00 UTC
UAF v1.1
Client tests
Tool Version 0.8.28 

Client gets request: 
`{"uafProtocolMessage":"[{"header":{"upv":{"major":1,"minor":1},"op":"Auth","appID":"","serverData":"5s7n8-7_LDAtRIKKYqbAtTTOezVKCjl2mPorYzbpxRrZ-_3wWroMXsF_pLYjNVm_l7bplAx4bkEwK6ibil9EHGfdfKOQ1q0tyEkNJFOgqdjVmLioroxgThlj8Istpt7q"},"challenge":"HQ1VkTUQC1NJDOo6OOWdxewrb9i5WthjfKIehFxpeuU","policy":{"accepted":[[{"aaid":["FFFF#FFFF"]}],[{"aaid":["4e4e#4091"]}],[{"aaid":["4e4e#4091"],"exts":[{"id":"unknown-id","data":"","fail_if_unknown":true}]}]]}}]"}
`
Expected result PROTOCOL_ERROR
Client returns SUCCESS as far as there is accepted separate criteria {"aaid":["4e4e#4091"]} registered authenticator matches this criteria, there is also criteria with extension with fail_if_unknown=true and client fails on matching this criteria but it still could successfully authenticate with first criteria.

**Comment by herrjemand** [comment] 2017-11-14 15:29
Duplicate of  #72

**Closed by herrjemand** 2017-11-14 15:29 UTC
